const questions=[
 {c:'Fit',q:'Tell us about yourself and why you are interested in this Service Design Researcher role.',a:`I started in customer experience research at the City of Toronto, working on resident-facing services including 311, affordable-housing research, accessibility-focused research practice, and the short-term-rental renewal service. At LCBO|next I moved closer to product delivery, using field research, interviews, UAT, service blueprinting and cross-functional workshops on Same Day Pickup. My current work adds two useful dimensions: at CAMH I support youth focus groups and co-design critiques for a DBT application; at Zephyr Bee Honey I combine customer feedback with live service and conversion data and implement improvements myself.\n\nThat combination is why this role fits. I know the public-service context, and I have since added stronger service-delivery, facilitation, prototyping and measurement experience.`,t:['public service','mixed-methods research','service design','311 Toronto']},
 {c:'Research',q:'Describe your experience leading mixed-methods service design research.',a:`I choose methods based on the uncertainty the team needs to reduce. At the City I combined large-sample resident-facing research with interviews and usability testing. For affordable housing, interviews with 15 low-income residents helped explain barriers that could not be understood from service data alone. At LCBO, field research, ethnographic observation, interviews and UAT exposed employee behaviours, constraints and workarounds, which I translated into a formal service blueprint and product requirements. More recently at Zephyr I use behavioural analytics alongside customer feedback and delivery constraints.\n\nThe point of mixing methods is that frequency and explanation are different questions. I use quantitative or operational evidence to establish patterns, then qualitative evidence to understand why they occur and what the team should test next.`,t:['mixed-methods','qualitative and quantitative','service blueprint','evidence-based recommendations']},
 {c:'Problem definition',q:'How do you define a service problem before starting research?',a:`I separate what is observed from what is assumed. I write down the decision the team is trying to make, the evidence already available, stakeholder claims that still need testing, and the service boundary. Then I prioritize the uncertainties that could change the decision.\n\nThat is the logic I used in the pothole assessment. The complaints tell us there is a confidence problem, but they do not establish whether the cause is intake, handoffs, operational status, resident-facing information or a combination. The research plan tests those conditions directly before recommending a redesign or new technology.`,t:['problem definition','discovery research','root cause','service boundary']},
 {c:'Inclusive research',q:'Tell us about your experience conducting inclusive and accessible research.',a:`At the City, I interviewed 15 low-income residents about the affordable-housing application journey and developed an Inclusive Research Design Framework informed by WCAG. That work made accessibility part of recruitment, participation and research planning rather than a final review step. I also coordinated accessible logistics across City studies involving more than 200 participants.\n\nCAMH is a current continuation of that practice. I support youth focus groups and co-design critiques for a DBT application, where feedback includes comprehension, cognitive load, accessibility and age-appropriate interaction design. I synthesize lived-experience perspectives and literature into recommendations clinicians and product stakeholders can use.`,t:['inclusive design research','lived experience','accessibility','WCAG']},
 {c:'Facilitation',q:'Describe your facilitation experience.',a:`At LCBO Innovation Lab I facilitated cross-functional PEGA workshops while the team was developing and operationalizing new product and service workflows. My job was to make the current process visible, capture operational constraints and turn discussion into documented decisions the product team could use. I also produced process documentation that supported adoption for up to 1,000 employees.\n\nI prepare facilitation around a specific decision or output. I make the activity concrete, give people more than one way to contribute, and document disagreements or unresolved questions rather than treating consensus as the only successful outcome.`,t:['facilitation','cross-functional','workshop','research documentation']},
 {c:'Stakeholders',q:'Tell us about a time you worked with stakeholders who had different perspectives or constraints.',a:`CAMH is a useful recent example because the work brings together youth lived experience, clinical requirements, research evidence, product constraints and privacy or safety considerations. In that kind of environment, I do not treat one perspective as automatically decisive. I make the underlying need and constraint explicit, use prototypes or evidence to make the issue concrete, and document what can be changed now versus what needs another decision.\n\nI used a similar principle in City work: resident evidence, program knowledge and technology constraints all matter, but they answer different questions.`,t:['stakeholder engagement','political awareness','good judgement','co-design']},
 {c:'Synthesis',q:'How do you analyze and synthesize qualitative and quantitative research?',a:`I keep findings traceable to source and separate observation, interpretation and recommendation. I organize evidence around the research question, look for patterns, contradictions and important exceptions, and keep enough case context to see where a service problem actually occurs.\n\nThen I compare evidence types. At the City, resident-facing research and usability evidence could explain why people behaved a certain way. At Zephyr, analytics tell me whether a pattern is widespread enough to prioritize. At CAMH, lived-experience feedback and literature help test whether a design interpretation is appropriate. I only combine those sources after being clear about what each one can support.`,t:['data collection and analysis','synthesis','qualitative and quantitative','triangulation']},
 {c:'Research impact',q:'Tell us about a time research changed the direction of your work.',a:`At Zephyr Bee Honey, delivery uncertainty initially looked like a content problem: customers needed clearer shipping and delivery information. Once I looked at the service rules and customer questions together, the issue was more structural. Eligibility depended on geography, delivery versus shipping, and discount logic. A paragraph of copy could not reliably answer that.\n\nI reframed the problem around helping a customer determine eligibility at the point of decision, then prototyped and implemented the interactive Delivery Zone. That is an example of research changing the form of the intervention rather than simply polishing the first idea.`,t:['problem definition','customer feedback','prototype','continuous improvement']},
 {c:'Fast pace',q:'Tell us about a time you delivered quality work under a tight deadline.',a:`LCBO|next was a fast product environment. Same Day Pickup needed research to inform decisions quickly enough that the team could keep moving toward MVP. I recruited and coordinated more than 15 employees for field research, interviews and UAT, documented operational behaviours and workarounds, and translated that into a service blueprint and requirements.\n\nUnder a short timeline, I protect the quality of the decision rather than trying to research everything. I keep the research question narrow, document assumptions and limitations, and test the highest-risk workflow first.`,t:['Agile','fast-paced multidisciplinary team','UAT','service blueprint']},
 {c:'Measurement',q:'How do you measure whether a service improvement worked?',a:`I start with the behaviour or operational effect the change is meant to influence and establish the baseline before evaluating the intervention. At Zephyr Bee Honey, I track sales, orders, conversion and checkout data alongside customer feedback, so I can see both what changed and possible explanations. The broader work contributed to strong quarter-over-quarter business results, but I am careful not to attribute every metric change to one feature.\n\nFor a City service I would use the same discipline with service-specific measures: successful request creation, duplicate-report rate, status visibility, avoidable follow-up contacts, comprehension and operational timing.`,t:['KPIs','baseline','continuous improvement','measurement plan']},
 {c:'Prototyping',q:'How do you use prototypes in research?',a:`I use the lowest fidelity that can answer the question. At LCBO, prototypes and UAT helped test store workflows before broader rollout. At the City, I contributed to blueprinting and prototyping the short-term-rental renewal service. At Zephyr, the Delivery Zone moved beyond prototype into implementation once the service logic was clear.\n\nThe prototype is evidence-generating material. Its value is the uncertainty it reduces, not how polished it looks.`,t:['rapid prototyping','evaluative research','proof of concept','iteration']},
 {c:'Tools',q:'What research and design tools do you use?',a:`My strongest hands-on tools include Figma, Miro, Adobe Creative Suite, Optimal Workshop, UserTesting, Lookback, PEGA, HTML and CSS. I have self-directed familiarity with Qualtrics and Dovetail rather than claiming the same production depth with those tools.\n\nI am comfortable learning the team's stack because the harder part is still research formulation, participant handling, analysis, documentation and choosing the right method for the decision.`,t:['Figma','Miro','research tools','accurate self-representation']},
 {c:'Public service',q:'Why public service, and why return to the City of Toronto?',a:`My City internship is where I learned how much a resident-facing experience depends on work behind the interface: program rules, technology, service operations, accessibility and what information residents can actually understand. The affordable-housing and 311 work also made the consequences of small service barriers very concrete.\n\nSince then I have added stronger product delivery, facilitation and measurement experience. Returning to the City now would let me bring that broader practice back to services where the outcome affects residents directly.`,t:['Toronto Public Service','resident-facing services','accessibility','service delivery']},
 {c:'Behavioural',q:'Tell us about a time you had to work independently when your manager or decision-maker was unavailable.',a:`My freelance work is the clearest example because I often own the path from an ambiguous request to a working service change. At Zephyr I have had to investigate customer questions, business rules and behavioural data, identify what actually needs to change, prototype it, implement it in Shopify and then monitor the result.\n\nWhen I am working independently, I document the decision, assumptions and dependencies so the client or stakeholder can review the reasoning later. I move ahead on reversible, well-supported decisions and escalate anything that changes policy, money, privacy or major operational commitments.`,t:['accountability','good judgement','independent work','documentation']},
 {c:'Presentation',q:'How do you communicate research findings to different audiences?',a:`I keep the evidence consistent but change the hierarchy. For research or program teams, I show methods, limitations, contradictory evidence and the path from observation to finding. For senior stakeholders, I lead with the decision, consequence and recommendation and keep the supporting detail available.\n\nAt the City I presented research and recommendations to more than 40 stakeholders. I have also presented product concepts to executive and cross-functional audiences. My visual design background helps, but I use visuals to make the service logic easier to understand rather than to decorate the finding.`,t:['stakeholder presentation','concise narratives','visual frameworks','research findings']},
 {c:'Presentation follow-up',q:'Why did you choose those four pothole-service assumptions?',a:`They correspond to four conditions that have to hold across the request lifecycle: the request is created, it remains connected as it moves across teams, operational decisions produce recorded statuses, and the status reaches the people who need it. Testing them lets the research locate the first point where the evidence diverges without assuming communication or technology is the cause.`,t:['validate assumptions','request lifecycle','discovery','root cause']},
 {c:'Presentation follow-up',q:'What would you do if Transportation Services says the process is working as intended?',a:`I would treat that as important operational expertise and a claim to examine. I would compare the documented process with actual case records and what residents and 311 can see. A process can comply with an internal procedure while still producing an external visibility or comprehension problem. The research needs to establish whether that is happening and under what conditions.`,t:['stakeholder perspective','operational evidence','good judgement','service standard']},
 {c:'Presentation follow-up',q:'What if the qualitative research and City records contradict one another?',a:`I would first check whether the sources are describing the same cases, population, period, channel and outcome. The disagreement may come from selection effects, missing records, different definitions or a metric that captures completion without capturing comprehension. I would treat the contradiction as a finding and design a focused follow-up test rather than choosing the source I prefer.`,t:['triangulation','data quality','qualitative and quantitative','follow-up research']},
 {c:'Presentation follow-up',q:'How would you determine sample size for this discovery?',a:`I would base sample size on the method, the variation that matters and the inference the team needs to make. Qualitative sample size is about covering relevant conditions and obtaining enough information to explain patterns, not estimating a population rate. For record analysis or channel comparisons, I would use enough cases to support the comparison and work with the City's data partners on what is statistically and operationally appropriate.`,t:['sampling','methodology','variation','data partners']},
 {c:'Presentation follow-up',q:'What if discovery shows that new technology is not required?',a:`Then I would not recommend new technology. The intervention should follow the verified cause. If the issue is content, process, ownership, service rules or data quality, the recommendation should address that layer and define a test and measure. The assessment explicitly starts before a redesign or technology decision, so a non-technology outcome is a valid discovery result.`,t:['evidence-based recommendation','process/policy/data','continuous improvement','technology-neutral']},
 {c:'Presentation follow-up',q:'What would success look like at the end of your six-week discovery?',a:`The City should be able to explain whether and where requests break down, how often, under what conditions, who is affected and why residents, 311 and Transportation experience the same service differently. The outputs should also make the next decision clear: prioritized findings, accountable owners, the next test or action, a baseline and a measurement plan.`,t:['current-state blueprint','prioritized findings','ownership','measurement']},
 {c:'Technical',q:'When would you use generative versus evaluative research?',a:`Generative research helps define the problem, context or unmet need when the team does not yet know what to build or change. Evaluative research tests an existing concept, prototype or service. I choose based on the decision. Early pothole discovery is mainly generative and diagnostic; a later prototype of a status message or workflow would be evaluative.`,t:['generative research','evaluative research','research formulation','decision']},
 {c:'Technical',q:'What makes co-design different from simply asking for feedback?',a:`I would call it co-design when participants or stakeholders materially help create, shape or prioritize options. Reviewing a prototype and giving feedback is useful, but it is not automatically co-design. At CAMH, youth engagement includes co-design critiques where lived-experience perspectives help shape age-appropriate and accessible interaction decisions.`,t:['co-design','lived experience','participation','accurate method language']}
];
let qIndex=Math.floor(Math.random()*questions.length);
function renderQuestion(){
 const q=questions[qIndex];document.getElementById('questionCategory').textContent=q.c;
 document.getElementById('questionText').textContent=q.q;document.getElementById('answerText').textContent=q.a;
 document.getElementById('answerText').classList.remove('show');document.getElementById('revealAnswer').textContent='Reveal exemplar';
 const box=document.getElementById('termsBox');box.classList.add('hidden');box.innerHTML='<hr><strong>Scoring terms:</strong> '+q.t.map(x=>`<span class="chip blue">${x}</span>`).join(' ');
 document.getElementById('drillNotes').value='';
 document.querySelectorAll('#scoreGrid button').forEach(b=>b.classList.remove('selected'));
}
document.getElementById('newQuestion').onclick=()=>{let n;do{n=Math.floor(Math.random()*questions.length)}while(n===qIndex);qIndex=n;renderQuestion()};
document.getElementById('revealAnswer').onclick=()=>{const a=document.getElementById('answerText'),b=document.getElementById('termsBox');const show=!a.classList.contains('show');a.classList.toggle('show',show);b.classList.toggle('hidden',!show);document.getElementById('revealAnswer').textContent=show?'Hide exemplar':'Reveal exemplar'};
renderQuestion();

let ansLeft=90,ansInt=null;
function renderAns(){const el=document.getElementById('answerTimer');el.textContent=fmt(Math.max(0,ansLeft));el.classList.toggle('warning',ansLeft<=20&&ansLeft>0);el.classList.toggle('over',ansLeft<=0)}
document.getElementById('answerStart').onclick=()=>{clearInterval(ansInt);ansLeft=90;renderAns();ansInt=setInterval(()=>{ansLeft--;renderAns();if(ansLeft<=0){clearInterval(ansInt);ansInt=null;beep(420,.25)}},1000)};
document.getElementById('answerReset').onclick=()=>{clearInterval(ansInt);ansInt=null;ansLeft=90;renderAns()};
document.querySelectorAll('#scoreGrid button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#scoreGrid button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.scores.push({q:questions[qIndex].q,score:+b.dataset.score,at:Date.now()});save();toast('Score saved')});
renderAns();
