// --- INTERVIEW ARCADE -------------------------------------------------------
const gameStoryNames = {
  housing:'City · Affordable housing + inclusive research',
  city311:'City · 311 + short-term rental',
  lcbo:'LCBO|next · Same Day Pickup',
  camh:'CAMH · Youth DBT app',
  zephyr:'Zephyr Bee Honey · Delivery Zone'
};

const storyGameRounds = [
  {cat:'Inclusive research',q:'Tell us about your experience conducting inclusive and accessible research.',correct:['housing','camh'],why:'Lead with City affordable housing because it gives you direct public-service evidence: 15 low-income residents, accessible research logistics and the Inclusive Research Design Framework. CAMH is a strong current follow-up.',cue:'15 residents → access barrier → inclusive framework → service/policy recommendation'},
  {cat:'Facilitation',q:'Describe your facilitation experience.',correct:['lcbo'],why:'LCBO is your clearest facilitation story because you can point to cross-functional PEGA workshops, operational constraints, documented decisions and adoption materials.',cue:'PEGA workshop → make process visible → constraints → decision/documentation'},
  {cat:'Fast pace',q:'Tell us about a time you delivered quality work under a tight deadline.',correct:['lcbo'],why:'LCBO gives you a fast MVP environment plus concrete research activity: 15+ employees, field research, interviews, UAT and service blueprinting.',cue:'MVP pressure → narrow question → highest-risk workflow → blueprint/UAT'},
  {cat:'Research changed direction',q:'Tell us about a time research changed the direction of your work.',correct:['zephyr'],why:'Zephyr gives you a clean change-of-direction story: what first looked like a content problem became a delivery eligibility and service-logic problem.',cue:'content assumption → customer questions + rules → eligibility logic → Delivery Zone'},
  {cat:'Stakeholders',q:'Tell us about a time you worked with stakeholders who had different perspectives or constraints.',correct:['camh','city311'],why:'CAMH is a strong current example because youth lived experience, clinical requirements, product constraints and privacy/safety considerations all have to be reconciled. City work is also valid.',cue:'need + constraint → evidence/prototype → what can change now → unresolved decision'},
  {cat:'Mixed methods',q:'Describe your mixed-methods service design research experience.',correct:['lcbo','housing'],why:'LCBO lets you combine field observation, ethnographic research, interviews and UAT in one service-delivery example. City housing is also useful when you want a public-service angle.',cue:'pattern/frequency ≠ explanation → choose methods by uncertainty → triangulate'},
  {cat:'Measurement',q:'How do you measure whether a service improvement worked?',correct:['zephyr'],why:'Zephyr is your strongest measurement story because you personally track sales, orders, conversion and checkout behaviour alongside customer feedback. Keep causality claims careful.',cue:'baseline → intended behaviour → KPI + feedback → monitor → avoid overclaiming'},
  {cat:'Prototyping',q:'How do you use prototypes in research?',correct:['city311','lcbo','zephyr'],why:'You have several valid choices. City short-term-rental renewal, LCBO UAT and Zephyr Delivery Zone all show prototypes reducing uncertainty. Pick based on the rest of the question.',cue:'lowest fidelity that answers the question → test uncertainty → iterate'},
  {cat:'Public service',q:'Why public service, and why return to the City of Toronto?',correct:['city311','housing'],why:'Use your City work. It gives you a credible reason grounded in resident-facing services, accessibility, program rules and the operational reality behind an interface.',cue:'City internship → resident consequences → broader skills since → bring them back'},
  {cat:'Communicating findings',q:'How do you communicate research findings to different audiences?',correct:['city311'],why:'City work gives you the strongest direct evidence: you presented research and recommendations to 40+ stakeholders and can explain how you change hierarchy without changing the evidence.',cue:'same evidence → different hierarchy → decision first for leaders → detail available'},
  {cat:'Problem definition',q:'How do you define a service problem before starting research?',correct:['zephyr','city311'],why:'Zephyr gives a concrete reframing example; your City pothole logic also demonstrates separating observations from assumptions and defining the service boundary.',cue:'observed → assumed → decision → uncertainty → service boundary'},
  {cat:'Independent work',q:'Tell us about a time you had to work independently when a manager or decision-maker was unavailable.',correct:['zephyr'],why:'Your freelance work gives you the clearest ownership story from ambiguity through investigation, implementation and monitoring.',cue:'investigate → document assumptions → reversible decision → escalate high-risk dependencies'}
];

const pathGameRounds = [
  {cat:'Slide 2 → Slide 3',q:'The brief gives three perspectives that do not yet form one explanation. What comes next in your logic?',options:['Choose a technology solution','Verify four service conditions','Write recommendations','Start with resident satisfaction scores'],answer:1,why:'Your presentation moves from unresolved perspectives to the current service conditions that need to be verified.',cue:'Perspectives unresolved → verify the process assumptions'},
  {cat:'Four conditions',q:'Which sequence is the exact memory anchor for Slide 3?',options:['Created → Connected → Recorded → Reached','Reported → Routed → Repaired → Resolved','Intake → Data → Operations → Content','Discover → Define → Design → Deliver'],answer:0,why:'Your four conditions are request created, request connected, operational decisions recorded, and status reaching the people who need it.',cue:'Created → Connected → Recorded → Reached'},
  {cat:'Primary tests',q:'What is the primary test for request creation?',options:['Status retrieval + comprehension','Reporting task + record match','Workflow observation only','Stakeholder workshop'],answer:1,why:'Slide 4 pairs a realistic reporting task with a City record match across available channels.',cue:'Attempt → identifiable record'},
  {cat:'Primary tests',q:'What is the primary test for request continuity?',options:['End-to-end request trace','Content comprehension test','Survey benchmark','Prototype preference test'],answer:0,why:'You trace selected requests across 311 and Transportation and inspect identity, ownership and history through handoffs.',cue:'Request → every handoff → identity/ownership/history'},
  {cat:'Analysis',q:'After analyzing each assumption at the appropriate unit, what is the next major synthesis move?',options:['Immediately recommend redesign','Place supported and qualified findings on a current-state service blueprint','Average all evidence into one score','Discard contradictory cases'],answer:1,why:'Slide 5 connects the separate validation streams by mapping supported and qualified findings onto the current-state service blueprint.',cue:'Analyze assumption → evidence statement → blueprint → interpretation check'},
  {cat:'Evidence statement',q:'Which set matches the evidence language in your presentation?',options:['Pass / fail / unknown','High / medium / low','Supported / supported under certain conditions / contradicted / insufficient evidence','Good / mixed / bad'],answer:2,why:'That four-part evidence statement protects uncertainty instead of forcing every assumption into a binary result.',cue:'Supported · conditional · contradicted · insufficient'},
  {cat:'Recommendations',q:'What should determine the type of recommendation?',options:['The most visible resident complaint','The verified cause','The newest technology available','Whichever team has budget'],answer:1,why:'Slide 6 explicitly lets the verified cause determine a proportionate response.',cue:'Verified cause → proportionate response'},
  {cat:'Close',q:'What makes discovery complete in your closing?',options:['A redesigned 311 interface is approved','The City can explain whether and where the process breaks, under what conditions, and why the three groups experience it differently','All stakeholders agree on one explanation','A new tracking system is selected'],answer:1,why:'Your close defines discovery success as an evidence-backed explanation that supports a defensible next step without assuming redesign or new technology.',cue:'where → conditions → why perspectives differ → defensible next step'}
];

let gameMode='story';
let gameCurrent=null;
let gameScoreData = state.gameScoreData || {score:0,streak:0,rounds:0};
function saveGame(){state.gameScoreData=gameScoreData;save();}
function renderGameStats(){document.getElementById('gameScore').textContent=gameScoreData.score;document.getElementById('gameStreak').textContent=gameScoreData.streak;document.getElementById('gameRound').textContent=gameScoreData.rounds;}
function chooseGameMode(mode){gameMode=mode;document.getElementById('modeStory').classList.toggle('active',mode==='story');document.getElementById('modePath').classList.toggle('active',mode==='path');document.getElementById('gameModeLabel').textContent=mode==='story'?'Story Match':'Presentation Path';document.getElementById('gamePrompt').textContent='Press “New round” to begin.';document.getElementById('gameChoices').innerHTML='';document.getElementById('gameSequence').innerHTML='';document.getElementById('gameFeedback').className='gamefeedback';document.getElementById('memoryCue').classList.add('hidden');document.getElementById('sayCueBtn').classList.add('hidden');document.getElementById('nextGameRound').classList.add('hidden');document.getElementById('gameCategory').textContent=mode==='story'?'Retrieval':'Presentation';}
function shuffled(arr){return [...arr].sort(()=>Math.random()-.5);}
function startGameRound(){const pool=gameMode==='story'?storyGameRounds:pathGameRounds;gameCurrent=pool[Math.floor(Math.random()*pool.length)];document.getElementById('gamePrompt').textContent=gameCurrent.q;document.getElementById('gameCategory').textContent=gameCurrent.cat;document.getElementById('gameFeedback').className='gamefeedback';document.getElementById('gameFeedback').innerHTML='';document.getElementById('memoryCue').classList.add('hidden');document.getElementById('memoryCue').innerHTML='';document.getElementById('sayCueBtn').classList.add('hidden');document.getElementById('nextGameRound').classList.add('hidden');const box=document.getElementById('gameChoices');box.innerHTML='';if(gameMode==='story'){const ids=shuffled(Object.keys(gameStoryNames));ids.forEach(id=>{const b=document.createElement('button');b.className='gamechoice';b.textContent=gameStoryNames[id];b.dataset.answer=id;b.onclick=()=>answerStoryGame(id,b);box.appendChild(b);});}else{gameCurrent.options.forEach((text,i)=>{const b=document.createElement('button');b.className='gamechoice';b.textContent=text;b.dataset.answer=i;b.onclick=()=>answerPathGame(i,b);box.appendChild(b);});}}
function finishGameRound(correct){document.querySelectorAll('#gameChoices .gamechoice').forEach(b=>b.disabled=true);gameScoreData.rounds++;if(correct){gameScoreData.streak++;gameScoreData.score += 100 + Math.min(gameScoreData.streak-1,5)*20;}else{gameScoreData.streak=0;}saveGame();renderGameStats();const f=document.getElementById('gameFeedback');f.className='gamefeedback show '+(correct?'good':'retry');f.innerHTML=`<strong>${correct?'✓ Strong retrieval choice':'↺ Another story is stronger for this prompt'}</strong><br>${gameCurrent.why}`;document.getElementById('sayCueBtn').classList.remove('hidden');document.getElementById('nextGameRound').classList.remove('hidden');}
function answerStoryGame(id,btn){const correct=gameCurrent.correct.includes(id);if(correct)btn.classList.add('correct');else btn.classList.add('wrong');document.querySelectorAll('#gameChoices .gamechoice').forEach(b=>{if(gameCurrent.correct.includes(b.dataset.answer))b.classList.add('correct');});finishGameRound(correct);}
function answerPathGame(index,btn){const correct=index===gameCurrent.answer;if(correct)btn.classList.add('correct');else btn.classList.add('wrong');document.querySelectorAll('#gameChoices .gamechoice').forEach(b=>{if(Number(b.dataset.answer)===gameCurrent.answer)b.classList.add('correct');});finishGameRound(correct);}
document.getElementById('modeStory').onclick=()=>chooseGameMode('story');
document.getElementById('modePath').onclick=()=>chooseGameMode('path');
document.getElementById('newGameRound').onclick=startGameRound;
document.getElementById('nextGameRound').onclick=startGameRound;
document.getElementById('sayCueBtn').onclick=()=>{const cue=document.getElementById('memoryCue');cue.innerHTML=`<strong>Memory cue:</strong> ${gameCurrent.cue}<br><span class="muted">Say the cue once, then answer the original prompt aloud without reading a script.</span>`;cue.classList.remove('hidden');};
document.getElementById('resetGameScore').onclick=()=>{if(confirm('Reset Interview Arcade score and streak?')){gameScoreData={score:0,streak:0,rounds:0};saveGame();renderGameStats();toast('Game score reset');}};
renderGameStats();
