const slides=[
 {n:'1',time:'0:00–0:45',target:'0:45',title:'Pothole reporting: from first attempt to final outcome',core:'Establish how the current service works before choosing a redesign or new technology.',script:`Good morning. I'm Thomass Muir. My background combines service research and product design. During my previous role in the City's Technology Services division, I worked on resident-facing services, including usability research for the 311 website.\n\nThe brief describes a pothole report that can begin through several channels and end with a resident who still does not know what happened. Before the City redesigns the service or introduces new technology, I would establish how the current process actually works from the first reporting attempt through the final outcome.`,transition:`The brief gives us three perspectives on that process, and they do not yet form one explanation.`},
 {n:'2',time:'0:45–1:55',target:'1:10',title:'Three perspectives leave the cause unresolved',core:'Treat each account as partial evidence, then define one end-to-end discovery question.',script:`Residents describe uncertainty at two points. They are unsure which channel to use, and some later lose sight of the request or report the pothole again. 311 representatives experience the result through calls from residents asking for updates. Transportation believes the process works as intended, while recognizing room to improve communication.\n\nAll three accounts may be accurate within the part of the service each group can see. The brief does not tell us how representative the complaints are, whether the same request remains visible across teams, or how an operational outcome becomes a public update.\n\nI would therefore bound discovery from the first reporting attempt through closure. I would look at the resident-facing journey, 311's view and Transportation's operational process, including attempts that never produce a reference number.\n\nMy central discovery question is: what happens from the first reporting attempt through closure, and where do the three accounts diverge?`,transition:`I would first verify the process that is assumed to sit behind those accounts.`},
 {n:'3',time:'1:55–3:10',target:'1:15',title:'Four service conditions to verify',core:'Validate assumptions about the current process — not proposed causes of the complaints.',script:`These are assumptions about how the current service operates. They are not proposed causes of the complaints.\n\nFirst, I am assuming that each reporting channel creates or routes an identifiable request into a defined workflow. Second, I am assuming that the request remains connected as it moves between 311 and Transportation, including when it is transferred, reassigned, merged or closed.\n\nThird, I am assuming that operational decisions produce recorded status changes. Fourth, I am assuming those statuses reach residents and 311 with enough detail to understand the progress and outcome.\n\nDiscovery may support an assumption across the service, support it only under certain conditions, contradict it, or show that the available evidence is insufficient. For each one, I want to know how often it holds, where it varies, who is affected and what explains the variation.`,transition:`Each assumption therefore needs its own primary test, supported by methods that explain the pattern.`},
 {n:'4',time:'3:10–5:30',target:'2:20',title:'Each assumption has one primary test',core:'Records establish the baseline; people and selected cases explain what the records miss and why results vary.',script:`For request creation, I would pair a realistic reporting task with a record match across available channels. I would confirm whether each attempt creates an identifiable record. Usability testing, channel comparisons and log review would explain incomplete or missing requests.\n\nFor continuity, I would trace selected requests across 311 and Transportation. Case walkthroughs, workflow interviews and cross-system review would test whether identity, ownership and history survive each handoff.\n\nFor status recording, I would observe Transportation's workflow and audit the corresponding records. I would compare the decision, procedure, recording time and resulting status.\n\nFor information access, I would test status retrieval and comprehension with residents and 311 representatives. Interviews, task testing, content review and delivery logs would show whether an update was available, reached the intended person and made sense to them.\n\nCity records establish a baseline for frequency and variation. They will not capture every failed attempt, informal workaround or misunderstanding. Tasks, observations, interviews and selected cases explain what the records miss and why results vary.\n\nWeek one would confirm the current process, definitions, data access, privacy requirements and recruitment. During weeks two to four, I would run the four primary tests and follow emerging differences by channel, outcome and access need. In weeks five and six, I would fill evidence gaps, examine contradictory cases and check the interpretation.\n\nResidents, the 311 Customer Experience Centre and Transportation Road Operations are the main evidence sources. Customer Experience and Transportation data teams, privacy, accessibility and language partners enable safe and inclusive research. I would lead the research, with the Customer Experience sponsor accountable for discovery decisions. The relevant operational, content, product or technology owner would lead the next test once the evidence identifies where action is needed.`,transition:`The four tests produce different evidence, so the analysis must begin at the level appropriate to each assumption.`},
 {n:'5',time:'5:30–7:15',target:'1:45',title:'Analyze each assumption, then connect the findings',core:'Analyze each validation stream at the right level, then synthesize the supported findings across the service.',script:`The four tests produce different kinds of evidence, so I would begin by analyzing each assumption at the appropriate level. For request creation, that may be the reporting attempt and the resulting record. For continuity, it is the request and each handoff. For operational recording, it is the decision and corresponding status event. For information access, it is the communication and what the resident or 311 representative could retrieve and understand.\n\nWithin each assumption, I would combine patterns in City records with evidence from tasks, observations, interviews and selected cases. I would examine frequency, variation, who is affected, possible explanations and evidence that contradicts the emerging interpretation. The result would be an evidence statement: supported, supported under certain conditions, contradicted or insufficient evidence.\n\nI would then place the supported and qualified findings onto a current-state service blueprint, from the first reporting attempt through status access and understanding. This would show whether an unclear outcome is associated with one condition or with several smaller issues that compound across the service. It would also preserve evidence about the places where the process works reliably.\n\nFinally, I would check different parts of the interpretation with the people best placed to assess them. Residents would check the reconstructed experience. 311 and Transportation would check workflow accuracy. Data owners would check how the records have been interpreted. Any disagreement or missing evidence would remain visible in the findings.`,transition:`Once the evidence shows what holds, where it varies and why, the City can choose a proportionate response.`},
 {n:'6',time:'7:15–8:30',target:'1:15',title:'Findings determine the next test, owner and measure',core:'Let the verified cause determine a proportionate response, with ownership and measurement defined before testing.',script:`The main outputs would be a current-state blueprint with supporting evidence, a prioritized findings and decision brief, and a test plan for the highest-priority response. Each finding would state the observed pattern, affected groups, supporting and contradictory evidence, confidence level and unresolved questions.\n\nRecommendations would follow the verified cause. If residents cannot interpret closure language, the next step may be a content test. If 311 cannot retrieve an operational update, the response may involve workflow or information access. If request identity breaks during a handoff, Transportation, Customer Experience and the relevant system owner would need to test a process or technical change together.\n\nFor the selected response, I would define an owner, baseline and measures before testing. Measures could include successful request creation, continuity across handoffs, time from an operational decision to a visible update, resident comprehension and repeat contact for status.\n\nDiscovery is complete when the City can explain whether and where the process breaks down, under what conditions, and why residents, 311 and Transportation experience it differently. That evidence gives the City a defensible next step without assuming in advance that the answer is a redesign or new technology.`,transition:`Pause. Look up. Invite questions.`}
];

let slideIdx=0;
function renderSlide(){
 const s=slides[slideIdx];
 document.getElementById('slideNumber').textContent=`Slide ${s.n} of 6 · ${s.time} · target ${s.target}`;
 const safeScript=s.script.replace(/\n/g,'<br>');
 document.getElementById('slideCard').innerHTML=`<div class="slidebox" style="margin-top:12px">
   <div class="slidehead">${s.title}</div>
   <div class="slidebody">
     <div class="row" style="margin-bottom:10px"><span class="chip blue">${s.time}</span><span class="chip">Target ${s.target}</span></div>
     <div class="callout gold"><strong>CORE POINT — NOT SPOKEN</strong><br>${s.core}</div>
     <div style="margin-top:14px"><div class="kicker">SCRIPT</div><p style="font-size:17px;line-height:1.58">${safeScript}</p></div>
     <div class="callout"><strong>TRANSITION — LOOK UP, THEN SAY</strong><br>${s.transition}</div>
   </div>
 </div>`;
 document.querySelectorAll('#assumptionAnchor div').forEach((d,i)=>d.classList.toggle('current',slideIdx===2));
}
renderSlide();
document.getElementById('prevSlide').onclick=()=>{slideIdx=Math.max(0,slideIdx-1);renderSlide()};
document.getElementById('nextSlide').onclick=()=>{slideIdx=Math.min(slides.length-1,slideIdx+1);renderSlide()};

let presSec=0,presInt=null;
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function beep(freq=700,dur=.12){try{const ac=new (window.AudioContext||window.webkitAudioContext)();const o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;o.connect(g);g.connect(ac.destination);o.start();g.gain.setValueAtTime(.15,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+dur);o.stop(ac.currentTime+dur)}catch(e){}}
function renderPresTimer(){
 const el=document.getElementById('presTimer');el.textContent=fmt(presSec);
 el.classList.toggle('warning',presSec>=540&&presSec<600);el.classList.toggle('over',presSec>=600);
}
document.getElementById('presStart').onclick=()=>{if(presInt)return;presInt=setInterval(()=>{presSec++;if(presSec===540)beep(650,.18);if(presSec===600)beep(400,.3);renderPresTimer()},1000)};
document.getElementById('presPause').onclick=()=>{clearInterval(presInt);presInt=null};
document.getElementById('presReset').onclick=()=>{clearInterval(presInt);presInt=null;presSec=0;renderPresTimer()};
renderPresTimer();
