const stories=[
 {id:'housing',name:'City · Affordable housing + inclusive research',facts:['Interviewed 15 low-income residents about the affordable-housing journey.','Translated lived-experience insights into service and policy recommendations.','Developed an Inclusive Research Design Framework informed by WCAG.','Useful for inclusion, resident engagement, accessibility, public-sector judgement and policy/service recommendations.'],prompt:'What barrier did residents face? What did you personally do in the sessions and analysis? What changed in the recommendation?'},
 {id:'city311',name:'City · 311 + short-term-rental renewal',facts:['Coordinated accessible research logistics across resident-facing studies involving 200+ participants.','Led interviews and usability testing to improve 311 information hierarchy and service usability.','Collaborated with program and technology stakeholders to research, blueprint and prototype short-term-rental renewal.','Presented findings to 40+ stakeholders.'],prompt:'Pick one specific finding or decision. What did the research show that stakeholders could act on?'},
 {id:'lcbo',name:'LCBO|next · Same Day Pickup',facts:['Recruited and coordinated 15+ store employees for field research, ethnographic observation, interviews and UAT.','Created a formal service blueprint across customer actions, frontstage workflows, backstage systems and handoffs.','Facilitated cross-functional PEGA workshops and created process documentation.','Service launched across 650+ stores; project reported a 50% reduction in fulfilment time.'],prompt:'What operational behaviour or workaround did you observe? How did it change the blueprint, requirement or prototype?'},
 {id:'camh',name:'CAMH · Youth Advisory Council / DBT app',facts:['Supported facilitated youth focus groups and co-design critiques.','Evaluated prototypes for usability, accessibility, comprehension and cognitive-load issues.','Synthesized lived-experience perspectives and literature into age-appropriate, trauma-informed recommendations.','Useful for co-design, accessibility, lived experience, stakeholder constraints and multidisciplinary work.'],prompt:'Recall one specific youth concern, design implication or tradeoff you discussed with clinicians/product stakeholders.'},
 {id:'zephyr',name:'Zephyr Bee Honey · Live service improvement',facts:['Owned Shopify sales, orders, conversion and checkout KPIs alongside customer feedback and delivery constraints.','Prototyped and implemented an interactive Delivery Zone clarifying eligibility, delivery vs shipping and discount logic.','Translated evidence into content, navigation, merchandising and service changes.','Broader work contributed to +471% sales, +310% orders and +53% conversion QoQ; avoid assigning all causality to one feature.'],prompt:'Explain the moment you realized the issue was service eligibility/logic rather than only content. What evidence led you there?'}
];
function renderStories(){
 const box=document.getElementById('storyList');box.innerHTML='';
 stories.forEach(s=>{
   const d=document.createElement('div');d.className='story';
   d.innerHTML=`<h3>${s.name}<span class="chip ${state.stories[s.id]?'green':''}">${state.stories[s.id]?'Ready':'Practice'}</span></h3>
   <ul class="storyfacts">${s.facts.map(f=>`<li>${f}</li>`).join('')}</ul>
   <div class="callout gold"><strong>Recall prompt:</strong> ${s.prompt}</div>
   <label style="display:block;margin-top:10px"><strong>Your memory cue</strong></label>
   <textarea data-note="${s.id}" placeholder="Write only enough to trigger the real story…">${(state.storyNotes&&state.storyNotes[s.id])||''}</textarea>
   <div class="row" style="margin-top:8px"><button class="btn small" data-ready="${s.id}">${state.stories[s.id]?'Mark for review':'Mark ready'}</button></div>`;
   box.appendChild(d);
 });
 box.querySelectorAll('[data-note]').forEach(t=>t.oninput=e=>{state.storyNotes=state.storyNotes||{};state.storyNotes[e.target.dataset.note]=e.target.value;save()});
 box.querySelectorAll('[data-ready]').forEach(b=>b.onclick=()=>{const id=b.dataset.ready;state.stories[id]=!state.stories[id];save();renderStories()});
}
renderStories();

let panelSet=[],panelIdx=-1,panelPhase='prep',panelLeft=30,panelInt=null;
function updatePanelTimer(){document.getElementById('panelTimer').textContent=fmt(panelLeft);document.getElementById('panelPhase').textContent=panelPhase==='prep'?'Prep':panelPhase==='answer'?'Answer':'Panel writing'}
function panelTick(){panelLeft--;updatePanelTimer();if(panelLeft<=0){if(panelPhase==='prep'){panelPhase='answer';panelLeft=120;beep(700,.1)}else if(panelPhase==='answer'){panelPhase='writing';panelLeft=10;beep(540,.1)}else{clearInterval(panelInt);panelInt=null;beep(430,.16);document.getElementById('panelPhase').textContent='Ready for next'}updatePanelTimer();}}
function startPanelQuestion(){if(panelIdx<0||panelIdx>=panelSet.length)return;const q=questions[panelSet[panelIdx]];document.getElementById('panelQuestion').textContent=q.q;document.getElementById('panelCount').textContent=`${panelIdx+1} / 5`;['panelComp','panelStory','panelWords','panelClose'].forEach(id=>document.getElementById(id).value='');clearInterval(panelInt);panelPhase='prep';panelLeft=30;updatePanelTimer();panelInt=setInterval(panelTick,1000);}
document.getElementById('panelStart').onclick=()=>{panelSet=[];while(panelSet.length<5){const n=Math.floor(Math.random()*questions.length);if(!panelSet.includes(n))panelSet.push(n)}panelIdx=0;startPanelQuestion()};
document.getElementById('panelNext').onclick=()=>{if(panelIdx<0){document.getElementById('panelStart').click();return}if(panelIdx<4){panelIdx++;startPanelQuestion()}else toast('Panel complete')};
document.getElementById('panelReset').onclick=()=>{clearInterval(panelInt);panelInt=null;panelSet=[];panelIdx=-1;panelPhase='prep';panelLeft=30;updatePanelTimer();document.getElementById('panelQuestion').textContent='Press Start Panel.';document.getElementById('panelCount').textContent='0 / 5'};
updatePanelTimer();

const requirements=[
 ['Major responsibilities',[
  ['r1','Use Human-Centred Design to investigate root causes across technology, policy and process','City / pothole plan'],['r2','Organize and execute generative and evaluative research','City + LCBO'],['r3','Work across researchers, program areas, stakeholders, public and agencies','City + CAMH'],['r4','Lead workshops/facilitation and user engagement','LCBO'],['r5','Understand individual journeys and personal situations','City housing'],['r6','Work with product/business/technology; prototypes and service blueprints','LCBO + City'],['r7','Carry research through product iterations','LCBO + Zephyr'],['r8','Analyze findings into design/product recommendations','City + CAMH'],['r9','Recommend process/policy/data improvements and track KPIs','Zephyr + City'],['r10','Produce concise narratives and visual frameworks','City presentations'],['r11','Contextual research: field visits, ethnography, surveys, benchmarks','LCBO'],['r12','Develop interview questions / questionnaires / data collection materials','City + LCBO'],['r13','Use qualitative + quantitative evidence for process improvement','City + Zephyr'],['r14','Synthesize data into root-cause insights and implementation direction','City + LCBO'],['r15','Review digital design and ensure accessibility/inclusivity','CAMH + City'],['r16','Advocate findings to varied audiences','City + LCBO'],['r17','Share/teach design methods','LCBO workshops'],['r18','Coordinate research administration','City'],['r19','Prepare detailed research/background documentation','City + LCBO']
 ]],
 ['Key qualifications',[
  ['k1','Relevant post-secondary education','Waterloo GBDA'],['k2','Considerable mixed-methods service design research/evaluation','City + LCBO + current'],['k3','Problem definition, inclusive research, co-design, prototyping and analytics','City + CAMH + Zephyr'],['k4','Considerable facilitation experience','LCBO'],['k5','Research/design artifacts: prototypes, journeys, blueprints, reports','LCBO + City']
 ]],
 ['Also required',[
  ['a1','Interpret complex information and prepare detailed documentation','City + LCBO'],['a2','Research formulation, collection, analysis and synthesis','Across projects'],['a3','Build relationships with colleagues, clients and diverse communities','City + CAMH'],['a4','Cross-cultural/political awareness and good judgement','City + CAMH'],['a5','Simplify prototypes; critical thinking and problem solving','LCBO + Zephyr'],['a6','Fast-paced multidisciplinary work under deadlines','LCBO'],['a7','Knowledge of varied research/design tools','Figma + Miro + others'],['a8','Present effectively to varied audiences','City 40+ stakeholders'],['a9','Support equity, diversity and respectful workplaces','City + CAMH']
 ]]
];
function renderReqs(){const box=document.getElementById('reqList');box.innerHTML='';let total=0,done=0;requirements.forEach(([group,items])=>{const wrap=document.createElement('div');wrap.className='reqgroup';wrap.innerHTML=`<h3>${group}</h3>`;items.forEach(([id,text,story])=>{total++;if(state.requirements[id])done++;const row=document.createElement('label');row.className='reqitem';row.innerHTML=`<input type="checkbox" ${state.requirements[id]?'checked':''}><span>${text}</span><span class="reqstory">${story}</span>`;row.querySelector('input').onchange=e=>{state.requirements[id]=e.target.checked;save();renderReqs()};wrap.appendChild(row);});box.appendChild(wrap);});const p=Math.round(done/total*100);document.getElementById('reqPct').textContent=`${done}/${total} · ${p}%`;document.getElementById('reqBar').style.width=p+'%';}
renderReqs();

const quickTerms=['discovery research','mixed-methods','problem definition','root cause','inclusive research','facilitation','co-design','service blueprint','prototyping','synthesis','KPIs','continuous improvement','311 Toronto','good judgement'];
document.getElementById('quickTerms').innerHTML=quickTerms.map(t=>`<span class="chip blue">${t}</span>`).join('');
document.getElementById('resetAll').onclick=()=>{if(confirm('Reset all saved progress and notes in this app?')){localStorage.removeItem(STORE);location.reload()}};
['panelComp','panelStory','panelWords','panelClose'].forEach(id=>{const el=document.getElementById(id);el.value=(state[id]||'');el.oninput=()=>{state[id]=el.value;save()}});
